# Generated by Django 4.2.11 on 2024-04-03 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [migrations.RunSQL(sql='CREATE SCHEMA IF NOT EXISTS content;', reverse_sql='DROP SCHEMA content'),
                  migrations.CreateModel(
                      name='FilmWork',
                      fields=[
                          ('created', models.DateTimeField(auto_now_add=True)),
                          ('modified', models.DateTimeField(auto_now=True)),
                          ('id',
                           models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                          ('title', models.CharField(max_length=255, verbose_name='title')),
                          ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                          ('creation_date', models.DateField(blank=True, null=True, verbose_name='creation_date')),
                          ('rating', models.FloatField(blank=True, null=True,
                                                       validators=[django.core.validators.MinValueValidator(0),
                                                                   django.core.validators.MaxValueValidator(100)],
                                                       verbose_name='rating')),
                          ('type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'Show')], default='movie',
                                                    max_length=20, verbose_name='type')),
                          ('file_path',
                           models.FileField(blank=True, null=True, upload_to='movies/', verbose_name='file_path')),
                      ],
                      options={
                          'verbose_name': 'Film work',
                          'verbose_name_plural': 'Film works',
                          'db_table': 'content"."film_work',
                      },
                  ),
                  migrations.CreateModel(
                      name='Genre',
                      fields=[
                          ('created', models.DateTimeField(auto_now_add=True)),
                          ('modified', models.DateTimeField(auto_now=True)),
                          ('id',
                           models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                          ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                          ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                      ],
                      options={
                          'verbose_name': 'Genre',
                          'verbose_name_plural': 'Genres',
                          'db_table': 'content"."genre',
                      },
                  ),
                  migrations.CreateModel(
                      name='Person',
                      fields=[
                          ('created', models.DateTimeField(auto_now_add=True)),
                          ('modified', models.DateTimeField(auto_now=True)),
                          ('id',
                           models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                          ('full_name', models.CharField(max_length=255, unique=True, verbose_name='full_name')),
                      ],
                      options={
                          'verbose_name': 'Participant',
                          'verbose_name_plural': 'Participants',
                          'db_table': 'content"."person',
                      },
                  ),
                  migrations.CreateModel(
                      name='PersonFilmWork',
                      fields=[
                          ('created', models.DateTimeField(auto_now_add=True)),
                          ('id',
                           models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                          ('role', models.CharField(
                              choices=[('director', 'Director'), ('actor', 'Actor'), ('writer', 'Writer')],
                              max_length=20, verbose_name='role')),
                          ('film_work',
                           models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork',
                                             verbose_name='Film work')),
                          ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person',
                                                       verbose_name='Participant')),
                      ],
                      options={
                          'verbose_name': 'Film participant',
                          'verbose_name_plural': 'Film participants',
                          'db_table': 'content"."person_film_work',
                      },
                  ),
                  migrations.CreateModel(
                      name='GenreFilmWork',
                      fields=[
                          ('created', models.DateTimeField(auto_now_add=True)),
                          ('id',
                           models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                          ('film_work',
                           models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                          ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre',
                                                      verbose_name='Genre')),
                      ],
                      options={
                          'verbose_name': 'film genre',
                          'verbose_name_plural': 'film genre',
                          'db_table': 'content"."genre_film_work',
                      },
                  ),
                  migrations.AddField(
                      model_name='filmwork',
                      name='genres',
                      field=models.ManyToManyField(through='movies.GenreFilmWork', to='movies.genre'),
                  ),
                  migrations.AddField(
                      model_name='filmwork',
                      name='persons',
                      field=models.ManyToManyField(through='movies.PersonFilmWork', to='movies.person'),
                  ),
                  migrations.AddConstraint(
                      model_name='personfilmwork',
                      constraint=models.UniqueConstraint(fields=('film_work', 'person', 'role'),
                                                         name='film_work_person_role_unique_idx'),
                  ),
                  migrations.AddConstraint(
                      model_name='genrefilmwork',
                      constraint=models.UniqueConstraint(fields=('film_work', 'genre'), name='film_work_genre_idx'),
                  ),
                  migrations.AddIndex(
                      model_name='filmwork',
                      index=models.Index(fields=['creation_date', 'rating'], name='film_work_creatio_3335ac_idx'),
                  ),
                  migrations.AddIndex(
                      model_name='filmwork',
                      index=models.Index(fields=['title'], name='film_work_title_3625e7_idx'),
                  ),
                  ]
