version: '3.3'

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - movies_admin/config/.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend.local

volumes:
  postgres-data:

networks:
  backend.local:
    external: true

